spring.application.name=resume-ai-backend

spring.data.mongodb.uri=mongodb+srv://saravana200421_db_user:Saroo7373@cluster0.9vevpwu.mongodb.net/resumeai?retryWrites=true&w=majority&appName=Cluster0

server.port=8080